# Generated by Django 5.2.7 on 2025-10-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus_session', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newfocussession',
            old_name='duration_minutes',
            new_name='actual_duration_minutes',
        ),
        migrations.AddField(
            model_name='newfocussession',
            name='interrupted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newfocussession',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newfocussession',
            name='target_duration_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='newfocussession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('interrupted', 'Interrupted')], default='active', max_length=20),
        ),
    ]
