# Generated by Django 5.2.7 on 2025-10-20 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('focus_session', '0002_rename_duration_minutes_newfocussession_actual_duration_minutes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newfocussession',
            old_name='actual_duration_minutes',
            new_name='actual_duration_seconds',
        ),
        migrations.RenameField(
            model_name='newfocussession',
            old_name='target_duration_minutes',
            new_name='target_duration_seconds',
        ),
    ]
